version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090/

  server:
    build: ./server
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ShareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: postgres_shareit
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ShareIt
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root